[project]
name = "lambda-application"
version = "0.1.0"
description = "Lambda application code, decoupled from lambda-infrastructure"
readme = "README.md"
requires-python = ">=3.11"

dependencies = []

[dependency-groups]
dev = [
  "pytest>=8.3",
  "ruff>=0.12",
]
