# https://taskfile.dev

version: "3"

tasks:
  default:
    deps:
      - format
      - lint
      - test
    silent: true

  format:
    cmds:
      - ./scripts/format.sh
    silent: true

  lint:
    cmds:
      - ./scripts/lint.sh
    silent: true

  test:
    cmds:
      - ./scripts/test.sh
    silent: true
