# https://taskfile.dev

version: "3"

vars:
  DOCKER_IMAGE_NAME: lambda-application
  DOCKER_IMAGE_TAG:
    sh: ./scripts/get-version.sh
  DOCKER_IMAGE: "{{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}}"

tasks:
  default:
    cmds:
      - task: setup
      - task: format
      - task: lint
      - task: build
      - task: unit-test
      - task: integration-test
    silent: true

  setup:
    run: once
    cmds:
      - ./scripts/setup.sh

  get-version:
    run: once
    cmds:
      - ./scripts/get-version.sh

  format:
    run: once
    cmds:
      - ./scripts/format.sh

  lint:
    run: once
    cmds:
      - ./scripts/lint.sh

  build:
    run: once
    cmds:
      - ./scripts/build-image.sh

  unit-test:
    run: once
    cmds:
      - ./scripts/unit-test.sh

  integration-test-no-build:
    run: once
    cmds:
      - task: start-local-instance
      - defer: { task: stop-local-instance }
      - ./scripts/integration-test.sh

  integration-test:
    run: once
    deps:
      - build
    cmds:
      - task: start-local-instance
      - defer: { task: stop-local-instance }
      - ./scripts/integration-test.sh

  start-local-instance:
    desc: Start a local Lambda instance for testing
    run: once
    cmds:
      - ./scripts/local-instance.sh start {{.DOCKER_IMAGE}}

  stop-local-instance:
    desc: Stop the local Lambda instance
    run: once
    cmds:
      - ./scripts/local-instance.sh stop {{.DOCKER_IMAGE}}

  release-ecr:
    desc: Release the Docker image to ECR
    run: once
    deps:
      - build
    cmds:
      - ./scripts/release-ecr.sh

  release-ecr-no-build:
    desc: Release the Docker image to ECR without building it first
    run: once
    cmds:
      - ./scripts/release-ecr.sh
