# https://taskfile.dev

version: "3"

tasks:
  default:
    deps:
      - setup
      - format
      - lint
      - build
      - unit-test
    silent: true

  setup:
    cmds:
      - ./scripts/setup.sh

  format:
    cmds:
      - ./scripts/format.sh

  lint:
    cmds:
      - ./scripts/lint.sh

  unit-test:
    cmds:
      - ./scripts/unit-test.sh

  test:
    deps:
      - unit-test

  build:
    cmds:
      - ./scripts/build.sh
