name: Publish
on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write # Required to create tags & GitHub Releases

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-publish-${{ github.ref_name }}
      cancel-in-progress: false

    steps:
      # Use a merge queue to avoid `main` commit race conditions.
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v6.4.3
        with:
          version: latest

      - name: Install dependencies
        run: ./scripts/setup.sh

      - name: Bootstrap tag
        id: tag-bootstrap
        run: ./scripts/version-tag-bootstrap.sh true

      - name: Tag version
        id: tag-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: ./scripts/version-tag-id.sh

      - name: Build
        if: steps.tag-version.outputs.released == 'true'
        run: ./scripts/build.sh

      - name: Publish to GitHub
        id: publish-github
        if: steps.tag-version.outputs.released == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/publish.sh
