name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize

env:
  PYTHON_VERSION: "3.11"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6.4.3
        with:
          version: latest

      - name: Install dependencies
        run: ./scripts/setup.sh

      - name: Run linting
        run: ./scripts/lint.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6.4.3
        with:
          version: latest

      - name: Build
        run: ./scripts/build.sh

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6.4.3
        with:
          version: latest

      - name: Install dependencies
        run: ./scripts/setup.sh

      - name: Run unit tests
        run: ./scripts/unit-test.sh
